---
- name: Ensure fail2ban is installed
  apt:
    name: fail2ban
    state: present
    install_recommends: false
  notify:
    - notify restart fail2ban
  tags:
    - fail2ban

- name: Ensure fail2ban is configured
  template: 
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - notify restart fail2ban

- name: Ensure fail2ban starts on a fresh reboot
  service: 
    name: fail2ban 
    state: started 
    enabled: yes